/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function findProcessByPid(pid: number): ProcessInfo | null

export declare function findProcessesByName(name: string): Array<ProcessInfo>

export declare function getProcessCmdline(pid: number): string | null

export interface ProcessInfo {
  pid: number
  name: string
}
